### ISSUE TITLE
cannot run evaluation for semantic segmentation with the checkpoint

### ISSUE THREAD

**Issue by kaixin-bai** [yikaiw/TokenFusion#14]
I followed the README file to evaluate semantic segmentation, with the command below:
```bash
python3 main.py --gpu 0 --resume ./pretrained_models/model-best.pth.tar --evaluate
```
where the `model-best.pth.tar` is download from 
| Method | Backbone | Pixel Acc. (%) | Mean Acc. (%) | Mean IoU (%) | Download | 
|:-----------:|:-----------:|:-----------:|:-----------:|:-----------:|:-----------:|
|Ours| SegFormer-B3 | 78.7 | 67.5 | 54.8 | [Google Drive](https://drive.google.com/drive/folders/14fi8aABFYqGF7LYKHkiJazHA58OBW1AW?usp=sharing)|

and i got error message:
```bash
Loaded Segmenter mit_b1, ImageNet-Pre-Trained=True, #PARAMS=14.96M
Traceback (most recent call last):
  File "main.py", line 459, in <module>
    main()
  File "main.py", line 382, in main
    best_val, epoch_start = load_ckpt(args.resume, {'segmenter': segmenter})
  File "main.py", line 211, in load_ckpt
    v.load_state_dict(ckpt[k])
  File "/home/kb/anaconda3/envs/tokenfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.encoder.block1.2.norm1.ln_0.weight", "module.encoder.block1.2.norm1.ln_0.bias", "module.encoder.block1.2.norm1.ln_1.weight", "module.encoder.block1.2.norm1.ln_1.bias", "module.encoder.block1.2.attn.q.module.weight", "module.encoder.block1.2.attn.q.module.bias", "module.encoder.block1.2.attn.kv.module.weight", "module.encoder.block1.2.attn.kv.module.bias", "module.encoder.block1.2.attn.proj.module.weight", "module.encoder.block1.2.attn.proj.module.bias", "module.encoder.block1.2.attn.sr.module.weight", "module.encoder.block1.2.attn.sr.module.bias", "module.encoder.block1.2.attn.norm.ln_0.weight", "module.encoder.block1.2.attn.norm.ln_0.bias", "module.encoder.block1.2.attn.norm.ln_1.weight", "module.encoder.block1.2.attn.norm.ln_1.bias", "module.encoder.block1.2.norm2.ln_0.weight", "module.encoder.block1.2.norm2.ln_0.bias", "module.encoder.block1.2.norm2.ln_1.weight", "module.encoder.block1.2.norm2.ln_1.bias", "module.encoder.block1.2.mlp.fc1.module.weight", "module.encoder.block1.2.mlp.fc1.module.bias", "module.encoder.block1.2.mlp.dwconv.dwconv.weight", "module.encoder.block1.2.mlp.dwconv.dwconv.bias", "module.encoder.block1.2.mlp.fc2.module.weight", "module.encoder.block1.2.mlp.fc2.module.bias", "module.encoder.block2.2.norm1.ln_0.weight", "module.encoder.block2.2.norm1.ln_0.bias", "module.encoder.block2.2.norm1.ln_1.weight", "module.encoder.block2.2.norm1.ln_1.bias", "module.encoder.block2.2.attn.q.module.weight", "module.encoder.block2.2.attn.q.module.bias", "module.encoder.block2.2.attn.kv.module.weight", "module.encoder.block2.2.attn.kv.module.bias", "module.encoder.block2.2.attn.proj.module.weight", "module.encoder.block2.2.attn.proj.module.bias", "module.encoder.block2.2.attn.sr.module.weight", "module.encoder.block2.2.attn.sr.module.bias", "module.encoder.block2.2.attn.norm.ln_0.weight", "module.encoder.block2.2.attn.norm.ln_0.bias", "module.encoder.block2.2.attn.norm.ln_1.weight", "module.encoder.block2.2.attn.norm.ln_1.bias", "module.encoder.block2.2.norm2.ln_0.weight", "module.encoder.block2.2.norm2.ln_0.bias", "module.encoder.block2.2.norm2.ln_1.weight", "module.encoder.block2.2.norm2.ln_1.bias", "module.encoder.block2.2.mlp.fc1.module.weight", "module.encoder.block2.2.mlp.fc1.module.bias", "module.encoder.block2.2.mlp.dwconv.dwconv.weight", "module.encoder.block2.2.mlp.dwconv.dwconv.bias", "module.encoder.block2.2.mlp.fc2.module.weight", "module.encoder.block2.2.mlp.fc2.module.bias", "module.encoder.block2.3.norm1.ln_0.weight", "module.encoder.block2.3.norm1.ln_0.bias", "module.encoder.block2.3.norm1.ln_1.weight", "module.encoder.block2.3.norm1.ln_1.bias", "module.encoder.block2.3.attn.q.module.weight", "module.encoder.block2.3.attn.q.module.bias", "module.encoder.block2.3.attn.kv.module.weight", "module.encoder.block2.3.attn.kv.module.bias", "module.encoder.block2.3.attn.proj.module.weight", "module.encoder.block2.3.attn.proj.module.bias", "module.encoder.block2.3.attn.sr.module.weight", "module.encoder.block2.3.attn.sr.module.bias", "module.encoder.block2.3.attn.norm.ln_0.weight", "module.encoder.block2.3.attn.norm.ln_0.bias", "module.encoder.block2.3.attn.norm.ln_1.weight", "module.encoder.block2.3.attn.norm.ln_1.bias", "module.encoder.block2.3.norm2.ln_0.weight", "module.encoder.block2.3.norm2.ln_0.bias", "module.encoder.block2.3.norm2.ln_1.weight", "module.encoder.block2.3.norm2.ln_1.bias", "module.encoder.block2.3.mlp.fc1.module.weight", "module.encoder.block2.3.mlp.fc1.module.bias", "module.encoder.block2.3.mlp.dwconv.dwconv.weight", "module.encoder.block2.3.mlp.dwconv.dwconv.bias", "module.encoder.block2.3.mlp.fc2.module.weight", "module.encoder.block2.3.mlp.fc2.module.bias", "module.encoder.block3.2.norm1.ln_0.weight", "module.encoder.block3.2.norm1.ln_0.bias", "module.encoder.block3.2.norm1.ln_1.weight", "module.encoder.block3.2.norm1.ln_1.bias", "module.encoder.block3.2.attn.q.module.weight", "module.encoder.block3.2.attn.q.module.bias", "module.encoder.block3.2.attn.kv.module.weight", "module.encoder.block3.2.attn.kv.module.bias", "module.encoder.block3.2.attn.proj.module.weight", "module.encoder.block3.2.attn.proj.module.bias", "module.encoder.block3.2.attn.sr.module.weight", "module.encoder.block3.2.attn.sr.module.bias", "module.encoder.block3.2.attn.norm.ln_0.weight", "module.encoder.block3.2.attn.norm.ln_0.bias", "module.encoder.block3.2.attn.norm.ln_1.weight", "module.encoder.block3.2.attn.norm.ln_1.bias", "module.encoder.block3.2.norm2.ln_0.weight", "module.encoder.block3.2.norm2.ln_0.bias", "module.encoder.block3.2.norm2.ln_1.weight", "module.encoder.block3.2.norm2.ln_1.bias", "module.encoder.block3.2.mlp.fc1.module.weight", "module.encoder.block3.2.mlp.fc1.module.bias", "module.encoder.block3.2.mlp.dwconv.dwconv.weight", "module.encoder.block3.2.mlp.dwconv.dwconv.bias", "module.encoder.block3.2.mlp.fc2.module.weight", "module.encoder.block3.2.mlp.fc2.module.bias", "module.encoder.block3.3.norm1.ln_0.weight", "module.encoder.block3.3.norm1.ln_0.bias", "module.encoder.block3.3.norm1.ln_1.weight", "module.encoder.block3.3.norm1.ln_1.bias", "module.encoder.block3.3.attn.q.module.weight", "module.encoder.block3.3.attn.q.module.bias", "module.encoder.block3.3.attn.kv.module.weight", "module.encoder.block3.3.attn.kv.module.bias", "module.encoder.block3.3.attn.proj.module.weight", "module.encoder.block3.3.attn.proj.module.bias", "module.encoder.block3.3.attn.sr.module.weight", "module.encoder.block3.3.attn.sr.module.bias", "module.encoder.block3.3.attn.norm.ln_0.weight", "module.encoder.block3.3.attn.norm.ln_0.bias", "module.encoder.block3.3.attn.norm.ln_1.weight", "module.encoder.block3.3.attn.norm.ln_1.bias", "module.encoder.block3.3.norm2.ln_0.weight", "module.encoder.block3.3.norm2.ln_0.bias", "module.encoder.block3.3.norm2.ln_1.weight", "module.encoder.block3.3.norm2.ln_1.bias", "module.encoder.block3.3.mlp.fc1.module.weight", "module.encoder.block3.3.mlp.fc1.module.bias", "module.encoder.block3.3.mlp.dwconv.dwconv.weight", "module.encoder.block3.3.mlp.dwconv.dwconv.bias", "module.encoder.block3.3.mlp.fc2.module.weight", "module.encoder.block3.3.mlp.fc2.module.bias", "module.encoder.block3.4.norm1.ln_0.weight", "module.encoder.block3.4.norm1.ln_0.bias", "module.encoder.block3.4.norm1.ln_1.weight", "module.encoder.block3.4.norm1.ln_1.bias", "module.encoder.block3.4.attn.q.module.weight", "module.encoder.block3.4.attn.q.module.bias", "module.encoder.block3.4.attn.kv.module.weight", "module.encoder.block3.4.attn.kv.module.bias", "module.encoder.block3.4.attn.proj.module.weight", "module.encoder.block3.4.attn.proj.module.bias", "module.encoder.block3.4.attn.sr.module.weight", "module.encoder.block3.4.attn.sr.module.bias", "module.encoder.block3.4.attn.norm.ln_0.weight", "module.encoder.block3.4.attn.norm.ln_0.bias", "module.encoder.block3.4.attn.norm.ln_1.weight", "module.encoder.block3.4.attn.norm.ln_1.bias", "module.encoder.block3.4.norm2.ln_0.weight", "module.encoder.block3.4.norm2.ln_0.bias", "module.encoder.block3.4.norm2.ln_1.weight", "module.encoder.block3.4.norm2.ln_1.bias", "module.encoder.block3.4.mlp.fc1.module.weight", "module.encoder.block3.4.mlp.fc1.module.bias", "module.encoder.block3.4.mlp.dwconv.dwconv.weight", "module.encoder.block3.4.mlp.dwconv.dwconv.bias", "module.encoder.block3.4.mlp.fc2.module.weight", "module.encoder.block3.4.mlp.fc2.module.bias", "module.encoder.block3.5.norm1.ln_0.weight", "module.encoder.block3.5.norm1.ln_0.bias", "module.encoder.block3.5.norm1.ln_1.weight", "module.encoder.block3.5.norm1.ln_1.bias", "module.encoder.block3.5.attn.q.module.weight", "module.encoder.block3.5.attn.q.module.bias", "module.encoder.block3.5.attn.kv.module.weight", "module.encoder.block3.5.attn.kv.module.bias", "module.encoder.block3.5.attn.proj.module.weight", "module.encoder.block3.5.attn.proj.module.bias", "module.encoder.block3.5.attn.sr.module.weight", "module.encoder.block3.5.attn.sr.module.bias", "module.encoder.block3.5.attn.norm.ln_0.weight", "module.encoder.block3.5.attn.norm.ln_0.bias", "module.encoder.block3.5.attn.norm.ln_1.weight", "module.encoder.block3.5.attn.norm.ln_1.bias", "module.encoder.block3.5.norm2.ln_0.weight", "module.encoder.block3.5.norm2.ln_0.bias", "module.encoder.block3.5.norm2.ln_1.weight", "module.encoder.block3.5.norm2.ln_1.bias", "module.encoder.block3.5.mlp.fc1.module.weight", "module.encoder.block3.5.mlp.fc1.module.bias", "module.encoder.block3.5.mlp.dwconv.dwconv.weight", "module.encoder.block3.5.mlp.dwconv.dwconv.bias", "module.encoder.block3.5.mlp.fc2.module.weight", "module.encoder.block3.5.mlp.fc2.module.bias", "module.encoder.block3.6.norm1.ln_0.weight", "module.encoder.block3.6.norm1.ln_0.bias", "module.encoder.block3.6.norm1.ln_1.weight", "module.encoder.block3.6.norm1.ln_1.bias", "module.encoder.block3.6.attn.q.module.weight", "module.encoder.block3.6.attn.q.module.bias", "module.encoder.block3.6.attn.kv.module.weight", "module.encoder.block3.6.attn.kv.module.bias", "module.encoder.block3.6.attn.proj.module.weight", "module.encoder.block3.6.attn.proj.module.bias", "module.encoder.block3.6.attn.sr.module.weight", "module.encoder.block3.6.attn.sr.module.bias", "module.encoder.block3.6.attn.norm.ln_0.weight", "module.encoder.block3.6.attn.norm.ln_0.bias", "module.encoder.block3.6.attn.norm.ln_1.weight", "module.encoder.block3.6.attn.norm.ln_1.bias", "module.encoder.block3.6.norm2.ln_0.weight", "module.encoder.block3.6.norm2.ln_0.bias", "module.encoder.block3.6.norm2.ln_1.weight", "module.encoder.block3.6.norm2.ln_1.bias", "module.encoder.block3.6.mlp.fc1.module.weight", "module.encoder.block3.6.mlp.fc1.module.bias", "module.encoder.block3.6.mlp.dwconv.dwconv.weight", "module.encoder.block3.6.mlp.dwconv.dwconv.bias", "module.encoder.block3.6.mlp.fc2.module.weight", "module.encoder.block3.6.mlp.fc2.module.bias", "module.encoder.block3.7.norm1.ln_0.weight", "module.encoder.block3.7.norm1.ln_0.bias", "module.encoder.block3.7.norm1.ln_1.weight", "module.encoder.block3.7.norm1.ln_1.bias", "module.encoder.block3.7.attn.q.module.weight", "module.encoder.block3.7.attn.q.module.bias", "module.encoder.block3.7.attn.kv.module.weight", "module.encoder.block3.7.attn.kv.module.bias", "module.encoder.block3.7.attn.proj.module.weight", "module.encoder.block3.7.attn.proj.module.bias", "module.encoder.block3.7.attn.sr.module.weight", "module.encoder.block3.7.attn.sr.module.bias", "module.encoder.block3.7.attn.norm.ln_0.weight", "module.encoder.block3.7.attn.norm.ln_0.bias", "module.encoder.block3.7.attn.norm.ln_1.weight", "module.encoder.block3.7.attn.norm.ln_1.bias", "module.encoder.block3.7.norm2.ln_0.weight", "module.encoder.block3.7.norm2.ln_0.bias", "module.encoder.block3.7.norm2.ln_1.weight", "module.encoder.block3.7.norm2.ln_1.bias", "module.encoder.block3.7.mlp.fc1.module.weight", "module.encoder.block3.7.mlp.fc1.module.bias", "module.encoder.block3.7.mlp.dwconv.dwconv.weight", "module.encoder.block3.7.mlp.dwconv.dwconv.bias", "module.encoder.block3.7.mlp.fc2.module.weight", "module.encoder.block3.7.mlp.fc2.module.bias", "module.encoder.block3.8.norm1.ln_0.weight", "module.encoder.block3.8.norm1.ln_0.bias", "module.encoder.block3.8.norm1.ln_1.weight", "module.encoder.block3.8.norm1.ln_1.bias", "module.encoder.block3.8.attn.q.module.weight", "module.encoder.block3.8.attn.q.module.bias", "module.encoder.block3.8.attn.kv.module.weight", "module.encoder.block3.8.attn.kv.module.bias", "module.encoder.block3.8.attn.proj.module.weight", "module.encoder.block3.8.attn.proj.module.bias", "module.encoder.block3.8.attn.sr.module.weight", "module.encoder.block3.8.attn.sr.module.bias", "module.encoder.block3.8.attn.norm.ln_0.weight", "module.encoder.block3.8.attn.norm.ln_0.bias", "module.encoder.block3.8.attn.norm.ln_1.weight", "module.encoder.block3.8.attn.norm.ln_1.bias", "module.encoder.block3.8.norm2.ln_0.weight", "module.encoder.block3.8.norm2.ln_0.bias", "module.encoder.block3.8.norm2.ln_1.weight", "module.encoder.block3.8.norm2.ln_1.bias", "module.encoder.block3.8.mlp.fc1.module.weight", "module.encoder.block3.8.mlp.fc1.module.bias", "module.encoder.block3.8.mlp.dwconv.dwconv.weight", "module.encoder.block3.8.mlp.dwconv.dwconv.bias", "module.encoder.block3.8.mlp.fc2.module.weight", "module.encoder.block3.8.mlp.fc2.module.bias", "module.encoder.block3.9.norm1.ln_0.weight", "module.encoder.block3.9.norm1.ln_0.bias", "module.encoder.block3.9.norm1.ln_1.weight", "module.encoder.block3.9.norm1.ln_1.bias", "module.encoder.block3.9.attn.q.module.weight", "module.encoder.block3.9.attn.q.module.bias", "module.encoder.block3.9.attn.kv.module.weight", "module.encoder.block3.9.attn.kv.module.bias", "module.encoder.block3.9.attn.proj.module.weight", "module.encoder.block3.9.attn.proj.module.bias", "module.encoder.block3.9.attn.sr.module.weight", "module.encoder.block3.9.attn.sr.module.bias", "module.encoder.block3.9.attn.norm.ln_0.weight", "module.encoder.block3.9.attn.norm.ln_0.bias", "module.encoder.block3.9.attn.norm.ln_1.weight", "module.encoder.block3.9.attn.norm.ln_1.bias", "module.encoder.block3.9.norm2.ln_0.weight", "module.encoder.block3.9.norm2.ln_0.bias", "module.encoder.block3.9.norm2.ln_1.weight", "module.encoder.block3.9.norm2.ln_1.bias", "module.encoder.block3.9.mlp.fc1.module.weight", "module.encoder.block3.9.mlp.fc1.module.bias", "module.encoder.block3.9.mlp.dwconv.dwconv.weight", "module.encoder.block3.9.mlp.dwconv.dwconv.bias", "module.encoder.block3.9.mlp.fc2.module.weight", "module.encoder.block3.9.mlp.fc2.module.bias", "module.encoder.block3.10.norm1.ln_0.weight", "module.encoder.block3.10.norm1.ln_0.bias", "module.encoder.block3.10.norm1.ln_1.weight", "module.encoder.block3.10.norm1.ln_1.bias", "module.encoder.block3.10.attn.q.module.weight", "module.encoder.block3.10.attn.q.module.bias", "module.encoder.block3.10.attn.kv.module.weight", "module.encoder.block3.10.attn.kv.module.bias", "module.encoder.block3.10.attn.proj.module.weight", "module.encoder.block3.10.attn.proj.module.bias", "module.encoder.block3.10.attn.sr.module.weight", "module.encoder.block3.10.attn.sr.module.bias", "module.encoder.block3.10.attn.norm.ln_0.weight", "module.encoder.block3.10.attn.norm.ln_0.bias", "module.encoder.block3.10.attn.norm.ln_1.weight", "module.encoder.block3.10.attn.norm.ln_1.bias", "module.encoder.block3.10.norm2.ln_0.weight", "module.encoder.block3.10.norm2.ln_0.bias", "module.encoder.block3.10.norm2.ln_1.weight", "module.encoder.block3.10.norm2.ln_1.bias", "module.encoder.block3.10.mlp.fc1.module.weight", "module.encoder.block3.10.mlp.fc1.module.bias", "module.encoder.block3.10.mlp.dwconv.dwconv.weight", "module.encoder.block3.10.mlp.dwconv.dwconv.bias", "module.encoder.block3.10.mlp.fc2.module.weight", "module.encoder.block3.10.mlp.fc2.module.bias", "module.encoder.block3.11.norm1.ln_0.weight", "module.encoder.block3.11.norm1.ln_0.bias", "module.encoder.block3.11.norm1.ln_1.weight", "module.encoder.block3.11.norm1.ln_1.bias", "module.encoder.block3.11.attn.q.module.weight", "module.encoder.block3.11.attn.q.module.bias", "module.encoder.block3.11.attn.kv.module.weight", "module.encoder.block3.11.attn.kv.module.bias", "module.encoder.block3.11.attn.proj.module.weight", "module.encoder.block3.11.attn.proj.module.bias", "module.encoder.block3.11.attn.sr.module.weight", "module.encoder.block3.11.attn.sr.module.bias", "module.encoder.block3.11.attn.norm.ln_0.weight", "module.encoder.block3.11.attn.norm.ln_0.bias", "module.encoder.block3.11.attn.norm.ln_1.weight", "module.encoder.block3.11.attn.norm.ln_1.bias", "module.encoder.block3.11.norm2.ln_0.weight", "module.encoder.block3.11.norm2.ln_0.bias", "module.encoder.block3.11.norm2.ln_1.weight", "module.encoder.block3.11.norm2.ln_1.bias", "module.encoder.block3.11.mlp.fc1.module.weight", "module.encoder.block3.11.mlp.fc1.module.bias", "module.encoder.block3.11.mlp.dwconv.dwconv.weight", "module.encoder.block3.11.mlp.dwconv.dwconv.bias", "module.encoder.block3.11.mlp.fc2.module.weight", "module.encoder.block3.11.mlp.fc2.module.bias", "module.encoder.block3.12.norm1.ln_0.weight", "module.encoder.block3.12.norm1.ln_0.bias", "module.encoder.block3.12.norm1.ln_1.weight", "module.encoder.block3.12.norm1.ln_1.bias", "module.encoder.block3.12.attn.q.module.weight", "module.encoder.block3.12.attn.q.module.bias", "module.encoder.block3.12.attn.kv.module.weight", "module.encoder.block3.12.attn.kv.module.bias", "module.encoder.block3.12.attn.proj.module.weight", "module.encoder.block3.12.attn.proj.module.bias", "module.encoder.block3.12.attn.sr.module.weight", "module.encoder.block3.12.attn.sr.module.bias", "module.encoder.block3.12.attn.norm.ln_0.weight", "module.encoder.block3.12.attn.norm.ln_0.bias", "module.encoder.block3.12.attn.norm.ln_1.weight", "module.encoder.block3.12.attn.norm.ln_1.bias", "module.encoder.block3.12.norm2.ln_0.weight", "module.encoder.block3.12.norm2.ln_0.bias", "module.encoder.block3.12.norm2.ln_1.weight", "module.encoder.block3.12.norm2.ln_1.bias", "module.encoder.block3.12.mlp.fc1.module.weight", "module.encoder.block3.12.mlp.fc1.module.bias", "module.encoder.block3.12.mlp.dwconv.dwconv.weight", "module.encoder.block3.12.mlp.dwconv.dwconv.bias", "module.encoder.block3.12.mlp.fc2.module.weight", "module.encoder.block3.12.mlp.fc2.module.bias", "module.encoder.block3.13.norm1.ln_0.weight", "module.encoder.block3.13.norm1.ln_0.bias", "module.encoder.block3.13.norm1.ln_1.weight", "module.encoder.block3.13.norm1.ln_1.bias", "module.encoder.block3.13.attn.q.module.weight", "module.encoder.block3.13.attn.q.module.bias", "module.encoder.block3.13.attn.kv.module.weight", "module.encoder.block3.13.attn.kv.module.bias", "module.encoder.block3.13.attn.proj.module.weight", "module.encoder.block3.13.attn.proj.module.bias", "module.encoder.block3.13.attn.sr.module.weight", "module.encoder.block3.13.attn.sr.module.bias", "module.encoder.block3.13.attn.norm.ln_0.weight", "module.encoder.block3.13.attn.norm.ln_0.bias", "module.encoder.block3.13.attn.norm.ln_1.weight", "module.encoder.block3.13.attn.norm.ln_1.bias", "module.encoder.block3.13.norm2.ln_0.weight", "module.encoder.block3.13.norm2.ln_0.bias", "module.encoder.block3.13.norm2.ln_1.weight", "module.encoder.block3.13.norm2.ln_1.bias", "module.encoder.block3.13.mlp.fc1.module.weight", "module.encoder.block3.13.mlp.fc1.module.bias", "module.encoder.block3.13.mlp.dwconv.dwconv.weight", "module.encoder.block3.13.mlp.dwconv.dwconv.bias", "module.encoder.block3.13.mlp.fc2.module.weight", "module.encoder.block3.13.mlp.fc2.module.bias", "module.encoder.block3.14.norm1.ln_0.weight", "module.encoder.block3.14.norm1.ln_0.bias", "module.encoder.block3.14.norm1.ln_1.weight", "module.encoder.block3.14.norm1.ln_1.bias", "module.encoder.block3.14.attn.q.module.weight", "module.encoder.block3.14.attn.q.module.bias", "module.encoder.block3.14.attn.kv.module.weight", "module.encoder.block3.14.attn.kv.module.bias", "module.encoder.block3.14.attn.proj.module.weight", "module.encoder.block3.14.attn.proj.module.bias", "module.encoder.block3.14.attn.sr.module.weight", "module.encoder.block3.14.attn.sr.module.bias", "module.encoder.block3.14.attn.norm.ln_0.weight", "module.encoder.block3.14.attn.norm.ln_0.bias", "module.encoder.block3.14.attn.norm.ln_1.weight", "module.encoder.block3.14.attn.norm.ln_1.bias", "module.encoder.block3.14.norm2.ln_0.weight", "module.encoder.block3.14.norm2.ln_0.bias", "module.encoder.block3.14.norm2.ln_1.weight", "module.encoder.block3.14.norm2.ln_1.bias", "module.encoder.block3.14.mlp.fc1.module.weight", "module.encoder.block3.14.mlp.fc1.module.bias", "module.encoder.block3.14.mlp.dwconv.dwconv.weight", "module.encoder.block3.14.mlp.dwconv.dwconv.bias", "module.encoder.block3.14.mlp.fc2.module.weight", "module.encoder.block3.14.mlp.fc2.module.bias", "module.encoder.block3.15.norm1.ln_0.weight", "module.encoder.block3.15.norm1.ln_0.bias", "module.encoder.block3.15.norm1.ln_1.weight", "module.encoder.block3.15.norm1.ln_1.bias", "module.encoder.block3.15.attn.q.module.weight", "module.encoder.block3.15.attn.q.module.bias", "module.encoder.block3.15.attn.kv.module.weight", "module.encoder.block3.15.attn.kv.module.bias", "module.encoder.block3.15.attn.proj.module.weight", "module.encoder.block3.15.attn.proj.module.bias", "module.encoder.block3.15.attn.sr.module.weight", "module.encoder.block3.15.attn.sr.module.bias", "module.encoder.block3.15.attn.norm.ln_0.weight", "module.encoder.block3.15.attn.norm.ln_0.bias", "module.encoder.block3.15.attn.norm.ln_1.weight", "module.encoder.block3.15.attn.norm.ln_1.bias", "module.encoder.block3.15.norm2.ln_0.weight", "module.encoder.block3.15.norm2.ln_0.bias", "module.encoder.block3.15.norm2.ln_1.weight", "module.encoder.block3.15.norm2.ln_1.bias", "module.encoder.block3.15.mlp.fc1.module.weight", "module.encoder.block3.15.mlp.fc1.module.bias", "module.encoder.block3.15.mlp.dwconv.dwconv.weight", "module.encoder.block3.15.mlp.dwconv.dwconv.bias", "module.encoder.block3.15.mlp.fc2.module.weight", "module.encoder.block3.15.mlp.fc2.module.bias", "module.encoder.block3.16.norm1.ln_0.weight", "module.encoder.block3.16.norm1.ln_0.bias", "module.encoder.block3.16.norm1.ln_1.weight", "module.encoder.block3.16.norm1.ln_1.bias", "module.encoder.block3.16.attn.q.module.weight", "module.encoder.block3.16.attn.q.module.bias", "module.encoder.block3.16.attn.kv.module.weight", "module.encoder.block3.16.attn.kv.module.bias", "module.encoder.block3.16.attn.proj.module.weight", "module.encoder.block3.16.attn.proj.module.bias", "module.encoder.block3.16.attn.sr.module.weight", "module.encoder.block3.16.attn.sr.module.bias", "module.encoder.block3.16.attn.norm.ln_0.weight", "module.encoder.block3.16.attn.norm.ln_0.bias", "module.encoder.block3.16.attn.norm.ln_1.weight", "module.encoder.block3.16.attn.norm.ln_1.bias", "module.encoder.block3.16.norm2.ln_0.weight", "module.encoder.block3.16.norm2.ln_0.bias", "module.encoder.block3.16.norm2.ln_1.weight", "module.encoder.block3.16.norm2.ln_1.bias", "module.encoder.block3.16.mlp.fc1.module.weight", "module.encoder.block3.16.mlp.fc1.module.bias", "module.encoder.block3.16.mlp.dwconv.dwconv.weight", "module.encoder.block3.16.mlp.dwconv.dwconv.bias", "module.encoder.block3.16.mlp.fc2.module.weight", "module.encoder.block3.16.mlp.fc2.module.bias", "module.encoder.block3.17.norm1.ln_0.weight", "module.encoder.block3.17.norm1.ln_0.bias", "module.encoder.block3.17.norm1.ln_1.weight", "module.encoder.block3.17.norm1.ln_1.bias", "module.encoder.block3.17.attn.q.module.weight", "module.encoder.block3.17.attn.q.module.bias", "module.encoder.block3.17.attn.kv.module.weight", "module.encoder.block3.17.attn.kv.module.bias", "module.encoder.block3.17.attn.proj.module.weight", "module.encoder.block3.17.attn.proj.module.bias", "module.encoder.block3.17.attn.sr.module.weight", "module.encoder.block3.17.attn.sr.module.bias", "module.encoder.block3.17.attn.norm.ln_0.weight", "module.encoder.block3.17.attn.norm.ln_0.bias", "module.encoder.block3.17.attn.norm.ln_1.weight", "module.encoder.block3.17.attn.norm.ln_1.bias", "module.encoder.block3.17.norm2.ln_0.weight", "module.encoder.block3.17.norm2.ln_0.bias", "module.encoder.block3.17.norm2.ln_1.weight", "module.encoder.block3.17.norm2.ln_1.bias", "module.encoder.block3.17.mlp.fc1.module.weight", "module.encoder.block3.17.mlp.fc1.module.bias", "module.encoder.block3.17.mlp.dwconv.dwconv.weight", "module.encoder.block3.17.mlp.dwconv.dwconv.bias", "module.encoder.block3.17.mlp.fc2.module.weight", "module.encoder.block3.17.mlp.fc2.module.bias", "module.encoder.block4.2.norm1.ln_0.weight", "module.encoder.block4.2.norm1.ln_0.bias", "module.encoder.block4.2.norm1.ln_1.weight", "module.encoder.block4.2.norm1.ln_1.bias", "module.encoder.block4.2.attn.q.module.weight", "module.encoder.block4.2.attn.q.module.bias", "module.encoder.block4.2.attn.kv.module.weight", "module.encoder.block4.2.attn.kv.module.bias", "module.encoder.block4.2.attn.proj.module.weight", "module.encoder.block4.2.attn.proj.module.bias", "module.encoder.block4.2.norm2.ln_0.weight", "module.encoder.block4.2.norm2.ln_0.bias", "module.encoder.block4.2.norm2.ln_1.weight", "module.encoder.block4.2.norm2.ln_1.bias", "module.encoder.block4.2.mlp.fc1.module.weight", "module.encoder.block4.2.mlp.fc1.module.bias", "module.encoder.block4.2.mlp.dwconv.dwconv.weight", "module.encoder.block4.2.mlp.dwconv.dwconv.bias", "module.encoder.block4.2.mlp.fc2.module.weight", "module.encoder.block4.2.mlp.fc2.module.bias". 
```

**Comment by kaixin-bai** [comment]
After commenting out the part of the PyTorch source code that checks for unexpected keys when loading the checkpoint, I was able to proceed with inference normally. However, the inference results were very poor. The pre-trained model used was provided in the README.

```python
img = make_validation_img(inputs[0].data.cpu().numpy(),  # color image
                          inputs[1].data.cpu().numpy(),   # depth image
                          sample['mask'].data.cpu().numpy(),  # ground truth mask
                          output[np.newaxis,:])   # predicted semantic mask
```
![validate_1](https://github.com/yikaiw/TokenFusion/assets/38804949/c44b86d0-69da-40cb-89a7-f35c02785c4f)

**Comment by kaixin-bai** [comment]
change the [code](https://github.com/yikaiw/TokenFusion/blob/main/semantic_segmentation/main.py#L211) to `v.load_state_dict(ckpt[k], strict=False)` can solve the "unexpected keys" problems.

But the evaluation result is quite bad:
```bash
Epoch 0    (rgb)     glob_acc=11.14    mean_acc=5.10     IoU=1.81             (best)
Epoch 0    (depth)   glob_acc=9.72     mean_acc=3.85     IoU=1.39         
Epoch 0    (ens)     glob_acc=14.35    mean_acc=4.81     IoU=1.86             (best)
```

**Comment by kaixin-bai** [comment]
change `python3 main.py --gpu 0 --resume ./pretrained_models/model-best.pth.tar --evaluate` to `python3 main.py --gpu 0 --backbone mit_b3 --resume ./pretrained_models/model-best.pth.tar --evaluate` solve the evaluation problem, because the default backbone in main.py is mit_b0

**Comment by Norooa** [comment]
![image](https://github.com/yikaiw/TokenFusion/assets/52622427/60c722fe-e084-486c-80df-24b1f6d49f87)
if you load the chechpoint properly, you can get the right result.
